metadata:
  name: fedora-coreos
  summary: Fedora CoreOS ${releasever}

ostree-layers:
  - overlay/01custom

repos:
  - fedora
  - fedora-updates

recommends: false
readonly-executables: true

ignore-removed-users:
  - root
ignore-removed-groups:
  - root
etc-group-members:
  - sudo
  - systemd-journal
  - adm
  - wheel
  - input
  - video

packages:
  - fedora-repos-ostree
  - fedora-repos-archive

  # system-configuration
  - chrony
  - coreos-installer coreos-installer-bootinfra
  - cloud-utils-growpart
  - cryptsetup
  - device-mapper-multipath
  - e2fsprogs
  - lvm2
  - mdadm
  - sg3_utils
  - xfsprogs
  - shadow-utils
  - acl
  - selinux-policy-targeted
  - ssh-key-dir
  - zram-generator

  # fedora-coreos-base
  - iptables-nft
  - btrfs-progs
  - sssd-client
  - attr
  - openssl
  - ncurses
  - kbd
  - systemd-resolved
  - qed-firmware

  # networking-tools
  - hostname
  - iproute-tc
  - nftables
  - socat

  # user-experience
  - bash-completion
  - coreutils
  - file
  - jq
  - less
  - sudo
  - vim-minimal
  - bsdtar
  - bzip2
  - gzip
  - tar
  - xz
  - zstd
  - openssh-clients openssh-server
  - nvme-cli
  - lsof
  - which
  - pciutils

  # custom
  - systemd-networkd
  - ldns-utils
  - strace
  - avahi
  - amd-gpu-firmware intel-gpu-firmware nvidia-gpu-firmware

packages-x86_64:
  - thermald
  - amd-ucode-firmware

remove-from-packages:
  - [dbus-common, /usr/lib/sysusers.d/dbus.conf]