ostree-layers:
  - overlay/01custom

repos:
  - fedora
  - fedora-updates

recommends: false
readonly-executables: true

ignore-removed-users:
  - root
ignore-removed-groups:
  - root
etc-group-members:
  - sudo
  - systemd-journal
  - adm
  - wheel
  - input
  - video

packages:
  - fedora-repos-ostree
  - fedora-repos-archive
  # system-configuration
  - chrony
  - coreos-installer coreos-installer-bootinfra
  - cloud-utils-growpart
  - cryptsetup
  - device-mapper-multipath
  - e2fsprogs
  - lvm2
  - mdadm
  - sg3_utils
  - xfsprogs
  - passwd
  - shadow-utils
  - acl
  - selinux-policy-targeted

  # user-experience
  - bash-completion
  - coreutils
  - jq
  - less
  - sudo
  - vim-minimal
  - bsdtar
  - bzip2
  - gzip
  - tar
  - xz
  - zstd
  - openssh-clients openssh-server
  - crun criu criu-libs
  - nvme-cli

  # fedora-coreos-base
  - iptables-nft
  # - btrfs-progs
  - sssd-client
  - attr
  - openssl
  - lsof
  - ncurses
  - kbd
  - zram-generator
  - systemd-resolved
  - amd-gpu-firmware intel-gpu-firmware nvidia-gpu-firmware
  - amd-ucode-firmware
  - qed-firmware

  # networking-tools
  - iproute-tc
  - nftables
  - socat
  - wireless-regdb iw

  # custom
  - hostname
  - systemd-networkd
  - ssh-key-dir
  - ldns-utils
  - pciutils
  - rsync
  - strace
  - kernel
  - irqbalance

  # wifi firmware
  - atheros-firmware
  - iwlwifi-dvm-firmware
  - iwlwifi-mvm-firmware
  - libertas-firmware
  - mt7xxx-firmware
  - nxpwireless-firmware
  - realtek-firmware
  - tiwilink-firmware
  - brcmfmac-firmware

packages-x86_64:
  - thermald

remove-from-packages:
  - [dbus-common, /usr/lib/sysusers.d/dbus.conf]