repos:
  - rpmfusion-free
  - rpmfusion-free-updates
  - rpmfusion-nonfree
  - rpmfusion-nonfree-updates
  - selfhosted
  - selfhosted-noarch

remove-from-packages:
  - [podman, /etc/cni/net.d/.*]

packages:
  - fedora-release-silverblue

  ## from common.yaml
  - kernel
  - kernel-modules
  # - kernel-modules-extra
  # Do not include "full" Git as it brings in Perl
  - git-core
  # Explicitely add Git docs
  - git-core-doc
  - lvm2
  # - rpm-ostree
  # Required for compatibility with old bootloaders until we have bootupd
  # See https://github.com/fedora-silverblue/issue-tracker/issues/120
  # - ostree-grub2
  # Container management
  - buildah
  - podman
  - skopeo
  - toolbox
  # Provides terminal tools like clear, reset, tput, and tset
  - ncurses
  # Flatpak support
  - flatpak
  - xdg-desktop-portal
  # HFS filesystem tools for Apple hardware
  # See https://github.com/projectatomic/rpm-ostree/issues/1380
  # - hfsplus-tools
  # Contains default ostree remote config to be used on client's
  # system for fetching ostree update
  # - fedora-repos-ostree
  # the archive repo for more reliable package layering
  # https://github.com/coreos/fedora-coreos-tracker/issues/400
  # - fedora-repos-archive
  - langpacks-en

  ## from common-packages.yaml
  # - NetworkManager
  # - NetworkManager-bluetooth
  # - NetworkManager-config-connectivity-fedora
  # - NetworkManager-wifi
  # - NetworkManager-wwan
  - acl
  - alsa-ucm
  - alsa-utils
  - amd-gpu-firmware
  - at-spi2-atk
  - at-spi2-core
  - atheros-firmware
  - attr
  # - audit
  - b43-fwcutter
  - b43-openfwwf
  - basesystem
  - bash
  - bash-color-prompt
  - bash-completion
  - bc
  # - bind-utils
  - bluez-cups
  - brcmfmac-firmware
  # - brltty
  - btrfs-progs
  - bzip2
  - chrony
  # - cifs-utils
  - colord
  - compsize
  - coreutils
  - cpio
  - cryptsetup
  - cups
  - cups-browsed
  - cups-filters
  - curl
  # - cyrus-sasl-plain
  # - default-editor
  - default-fonts-cjk-mono
  - default-fonts-cjk-sans
  - default-fonts-cjk-serif
  - default-fonts-core-emoji
  - default-fonts-core-math
  - default-fonts-core-mono
  - default-fonts-core-sans
  - default-fonts-core-serif
  - default-fonts-other-mono
  - default-fonts-other-sans
  - default-fonts-other-serif
  # - dhcp-client
  # - dnsmasq
  - e2fsprogs
  - ethtool
  - exfatprogs
  # - fedora-bookmarks
  # - fedora-chromium-config
  - fedora-flathub-remote
  # - fedora-workstation-backgrounds
  # - fedora-workstation-repositories
  - file
  - filesystem
  # - firefox
  # - firewalld
  # - fpaste
  # - fros-gnome
  - fwupd
  - gamemode
  - glibc
  - glibc-all-langpacks
  - gnupg2
  - gstreamer1-plugin-libav
  - gstreamer1-plugins-bad-free
  - gstreamer1-plugins-good
  - gstreamer1-plugins-ugly-free
  - gutenprint
  - gutenprint-cups
  - hostname
  - hplip
  - hunspell
  - ibus-anthy
  - ibus-chewing
  - ibus-gtk3
  - ibus-gtk4
  - ibus-hangul
  - ibus-libpinyin
  - ibus-libzhuyin
  - ibus-m17n
  - ibus-typing-booster
  - intel-gpu-firmware
  - iproute-tc
  - iptables-nft
  - iptstate
  - iputils
  # - iwlegacy-firmware
  - iwlwifi-dvm-firmware
  - iwlwifi-mvm-firmware
  - kbd
  - less
  - libertas-firmware
  # - libglvnd-gles
  - linux-firmware
  # - logrotate
  - lrzsz
  - lsof
  - man-db
  - man-pages
  - mdadm
  - mpage
  - mt7xxx-firmware
  - mtr
  # - nfs-utils
  - nss-altfiles
  - nss-mdns
  # - ntfs-3g
  # - ntfsprogs
  - nvidia-gpu-firmware
  - nxpwireless-firmware
  - opensc
  - openssh-clients
  - openssh-server
  # - orca
  - pam_afs_session
  - paps
  - passwdqc
  - pciutils
  - pinfo
  - pipewire-alsa
  - pipewire-gstreamer
  - pipewire-pulseaudio
  - pipewire-utils
  - plocate
  # - plymouth
  # - plymouth-system-theme
  - policycoreutils
  # - policycoreutils-python-utils
  - procps-ng
  - psmisc
  - qemu-guest-agent
  # - qt5-qtbase
  # - qt5-qtbase-gui
  # - qt5-qtdeclarative
  # - qt5-qtxmlpatterns
  - quota
  - realmd
  - realtek-firmware
  - rootfiles
  - rpm
  - rpm-ostree
  - rsync
  # - samba-client
  - selinux-policy-targeted
  - setup
  - shadow-utils
  # - sos
  # - speech-dispatcher
  # - spice-vdagent
  # - spice-webdavd
  # - sssd-common
  # - sssd-kcm
  - sudo
  - system-config-printer-udev
  - systemd
  - systemd-oomd-defaults
  - systemd-resolved
  - systemd-udev
  - tar
  - time
  - tiwilink-firmware
  - toolbox
  - tree
  - unzip
  - uresourced
  - usb_modeswitch
  - usbutils
  - util-linux
  - vim-minimal
  - wget2-wget
  - which
  - whois
  - wireplumber
  - words
  - wpa_supplicant
  - zip
  - zram-generator-defaults

  ## from silverblue-packages.yaml
  # - ModemManager
  # - NetworkManager-adsl
  # - NetworkManager-openconnect-gnome
  # - NetworkManager-openvpn-gnome
  # - NetworkManager-ppp
  # - NetworkManager-pptp-gnome
  # - NetworkManager-ssh-gnome
  # - NetworkManager-vpnc-gnome
  # - NetworkManager-wwan
  - adobe-source-code-pro-fonts
  - at-spi2-atk
  - at-spi2-core
  - avahi
  - dconf
  - fprintd-pam
  - gdm
  - glib-networking
  # - gnome-backgrounds
  - gnome-bluetooth
  # - gnome-browser-connector
  # - gnome-classic-session
  - gnome-color-manager
  - gnome-control-center
  # - gnome-disk-utility
  # - gnome-initial-setup
  # - gnome-remote-desktop
  - gnome-session-wayland-session
  - gnome-settings-daemon
  - gnome-shell
  # - gnome-software
  # - gnome-system-monitor
  - gnome-terminal
  - gnome-terminal-nautilus
  # - gnome-user-docs
  # - gnome-user-share
  - gvfs-afc
  # - gvfs-afp
  - gvfs-archive
  - gvfs-fuse
  - gvfs-goa
  - gvfs-gphoto2
  - gvfs-mtp
  # - gvfs-smb
  - librsvg2
  - libsane-hpaio
  - mesa-dri-drivers
  - mesa-libEGL
  - mesa-vulkan-drivers
  - nautilus
  # - plymouth-system-theme
  - polkit
  # - rygel
  - systemd-oomd-defaults
  - tracker
  - tracker-miners
  - xdg-desktop-portal
  - xdg-desktop-portal-gnome
  - xdg-desktop-portal-gtk
  - xdg-user-dirs-gtk
  # - yelp

  # custom
  - intel-media-driver
  - mesa-va-drivers-freeworld mesa-vdpau-drivers-freeworld
  - passt netavark aardvark-dns containernetworking-plugins
  - libva-utils
  - vulkan vulkan-tools
  - tmux xclip
  - kubernetes-client helm
  - nmap
  - unar

  # peripherals
  - dymo-cups-drivers
  # https://www.reddit.com/r/Fedora/comments/ocn6ko/usb_tethering_with_ios_146_on_fedora/
  - libimobiledevice-utils usbmuxd