releasever: "37"

# This file is most of a Fedora CoreOS like system; it inherits from "core".
# Add things in this file which are somewhat "opinionated", not necessarily
# core functionality.
ref: fedora/${releasever}/${basearch}/coreos
include:
  - manifests/ignition-and-ostree.yaml

ostree-layers:
  - overlay/01custom

automatic-version-prefix: "${releasever}.<date:%Y%m%d>"
mutate-os-release: "${releasever}"

repos:
  - fedora
  - fedora-updates
  - fedora-modular
  - fedora-updates-modular
  - kubernetes
  - cri-o_1.24.0

# Be minimal
recommends: false

ignore-removed-users:
  - root
ignore-removed-groups:
  - root
etc-group-members:
  - sudo
  - systemd-journal
  - adm
  - wheel

remove-from-packages:
  - [conntrack-tools, /etc/conntrackd/conntrackd.conf]
  - [cri-o, /etc/cni/net.d/.*]

check-passwd:
  type: "file"
  filename: "manifests/passwd"
check-groups:
  type: "file"
  filename: "manifests/group"

rpmdb: sqlite

packages:
  # system-configuration
  - chrony
  - coreos-installer coreos-installer-bootinfra
  - cloud-utils-growpart
  - cryptsetup
  - device-mapper-multipath
  - e2fsprogs
  - iscsi-initiator-utils
  - lvm2
  - mdadm
  - sg3_utils
  - xfsprogs
  - passwd
  - shadow-utils
  - acl

  # user-experience
  - bash-completion
  - coreutils
  - jq
  - less
  - sudo
  - vim-minimal
  - bsdtar
  - bzip2
  - gzip
  - tar
  - xz
  - zstd
  - openssh-clients openssh-server
  - crun
  - nvme-cli

  # fedora-coreos-base
  - btrfs-progs
  - attr
  - openssl
  - lsof
  - ncurses
  - kbd
  - zram-generator
  - systemd-resolved

  # custom
  - hostname
  - systemd-networkd
  - iproute-tc
  - nftables iptables-nft
  - ldns-utils
  - socat
  - pciutils
  - ipvsadm
  - cri-o cri-tools conntrack-tools kubelet
  - hdparm
  - ssh-key-dir

packages-x86_64:
  - irqbalance
packages-ppc64le:
  - irqbalance
packages-aarch64:
  - irqbalance

exclude-packages:
  - python
  - python2
  - python2-libs
  # - python3
  # - python3-libs
  - perl
  # - perl-interpreter
  - nodejs
  - dnf
  # - grubby
  - cowsay
  - initscripts
  - plymouth
  - NetworkManager
  - PackageKit

arch-include:
  x86_64:
    - manifests/grub2-removals.yaml
    - manifests/bootupd.yaml
  aarch64:
    - manifests/grub2-removals.yaml
    - manifests/bootupd.yaml
  ppc64le:
    - manifests/grub2-removals.yaml
