"packages":
- "git-core"
- "git-core-doc"
- "lvm2"
- "buildah"
- "podman"
- "skopeo"
- "toolbox"
- "ncurses"
- "flatpak"
- "xdg-desktop-portal"
- "acl"
- "alsa-ucm"
- "alsa-utils"
- "amd-gpu-firmware"
- "atheros-firmware"
- "attr"
- "b43-fwcutter"
- "b43-openfwwf"
- "basesystem"
- "bash"
- "bash-color-prompt"
- "bash-completion"
- "bc"
- "bluez-cups"
- "brcmfmac-firmware"
- "btrfs-progs"
- "bzip2"
- "chrony"
- "colord"
- "compsize"
- "coreutils"
- "cpio"
- "cryptsetup"
- "cups"
- "cups-browsed"
- "cups-filters"
- "curl"
- "default-fonts-cjk-mono"
- "default-fonts-cjk-sans"
- "default-fonts-cjk-serif"
- "default-fonts-core-emoji"
- "default-fonts-core-math"
- "default-fonts-core-mono"
- "default-fonts-core-sans"
- "default-fonts-core-serif"
- "default-fonts-other-mono"
- "default-fonts-other-sans"
- "default-fonts-other-serif"
- "e2fsprogs"
- "ethtool"
- "exfatprogs"
- "fedora-flathub-remote"
- "file"
- "filesystem"
- "fwupd"
- "gamemode"
- "glibc"
- "glibc-all-langpacks"
- "gnupg2"
- "gstreamer1-plugin-libav"
- "gstreamer1-plugins-bad-free"
- "gstreamer1-plugins-good"
- "gstreamer1-plugins-ugly-free"
- "gutenprint"
- "gutenprint-cups"
- "hostname"
- "hplip"
- "hunspell"
- "ibus-anthy"
- "ibus-gtk3"
- "ibus-gtk4"
- "ibus-hangul"
- "ibus-libpinyin"
- "ibus-libzhuyin"
- "ibus-m17n"
- "ibus-typing-booster"
- "intel-gpu-firmware"
- "iptables-nft"
- "iptstate"
- "iputils"
- "iwlegacy-firmware"
- "iwlwifi-dvm-firmware"
- "iwlwifi-mvm-firmware"
- "kbd"
- "kernel"
- "kernel-modules-extra"
- "less"
- "libertas-firmware"
- "linux-firmware"
- "lrzsz"
- "lsof"
- "man-db"
- "man-pages"
- "mdadm"
- "mpage"
- "mt7xxx-firmware"
- "mtr"
- "nss-altfiles"
- "nss-mdns"
- "nvidia-gpu-firmware"
- "opensc"
- "openssh-clients"
- "openssh-server"
- "pam_afs_session"
- "paps"
- "passwd"
- "passwdqc"
- "pciutils"
- "pinfo"
- "pipewire-alsa"
- "pipewire-gstreamer"
- "pipewire-pulseaudio"
- "pipewire-utils"
- "plocate"
- "policycoreutils"
- "procps-ng"
- "psmisc"
- "qemu-guest-agent"
- "quota"
- "realmd"
- "realtek-firmware"
- "rootfiles"
- "rpm"
- "rsync"
- "selinux-policy-targeted"
- "setup"
- "shadow-utils"
- "sudo"
- "system-config-printer-udev"
- "systemd"
- "systemd-oomd-defaults"
- "systemd-resolved"
- "systemd-udev"
- "tar"
- "time"
- "toolbox"
- "tree"
- "unzip"
- "uresourced"
- "usb_modeswitch"
- "usbutils"
- "util-linux"
- "vim-minimal"
- "wget"
- "which"
- "whois"
- "wireplumber"
- "words"
- "wpa_supplicant"
- "zip"
- "zram-generator-defaults"
- "adobe-source-code-pro-fonts"
- "at-spi2-atk"
- "at-spi2-core"
- "avahi"
- "dconf"
- "fprintd-pam"
- "gdm"
- "glib-networking"
- "glx-utils"
- "gnome-bluetooth"
- "gnome-color-manager"
- "gnome-control-center"
- "gnome-session-wayland-session"
- "gnome-settings-daemon"
- "gnome-shell"
- "gnome-terminal"
- "gnome-terminal-nautilus"
- "gvfs-afc"
- "gvfs-archive"
- "gvfs-fuse"
- "gvfs-goa"
- "gvfs-gphoto2"
- "gvfs-mtp"
- "librsvg2"
- "libsane-hpaio"
- "mesa-dri-drivers"
- "mesa-libEGL"
- "mesa-vulkan-drivers"
- "nautilus"
- "polkit"
- "systemd-oomd-defaults"
- "tracker"
- "tracker-miners"
- "xdg-desktop-portal"
- "xdg-desktop-portal-gnome"
- "xdg-desktop-portal-wlr"
- "xdg-user-dirs-gtk"
- "mesa-va-drivers-freeworld mesa-vdpau-drivers-freeworld"
- "slirp4netns podman-plugins netavark aardvark-dns"
- "libva-utils"
- "vulkan vulkan-tools"
- "tmux xclip"
- "kubectl helm"
- "nmap"
- "sunshine"
- "intel-media-driver"
- "opentabletdriver"
- "dymo-cups-drivers"
- "libimobiledevice-utils usbmuxd"
"repos":
- "rpmfusion-free"
- "rpmfusion-free-updates"
- "rpmfusion-nonfree"
- "rpmfusion-nonfree-updates"
- "selfhosted"
- "tailscale-stable"
- "kubernetes"
