ID=fedora
NAME=fedora-coreos
STREAM=testing-devel
DESCRIPTION="Fedora CoreOS testing-devel"
VERSION=43
MUTATE_OS_RELEASE=43
BUILDER_IMG=quay.io/bootc-devel/fedora-bootc-43-standard:latest@sha256:0027121e398f0426c4b1c34e2d9f17afcbb057bd3fe476c5ec7f7bff1e6218d5
MANIFEST=manifest-custom.yaml
PASSWD_GROUP_DIR=manifests
IMAGE_CONFIG=image-custom.yaml
