name: Tag Test
on:
  workflow_dispatch:

env:
  # This needs to match releasever
  FEDORA_VERSION: 41

jobs:
  build:
    runs-on: arc-runner-${{ github.event.repository.name }}
    container:
      image: quay.io/coreos-assembler/coreos-assembler:latest
    permissions:
      contents: write
    steps:
    - name: Set tag
      run: |
        echo "BUILD_TAG=$(date -u +'%Y%m%d.%H%M')" | sudo tee -a "$GITHUB_ENV"

    - name: Build image
      env:
        VARIANT: coreos
        COSA_SUPERMIN_MEMORY: 4096
      run: |
        cd $HOME
        cosa init -V $VARIANT \
          --force ${{ github.server_url }}/${{ github.repository }}.git

        cat > src/config/override.yaml <<EOF
        releasever: $FEDORA_VERSION
        EOF

    - name: Create tag
      run: |
        cd $HOME/src/config
        echo "${{ github.actor }}"

        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"
        git tag -a $BUILD_TAG -m "Build f$FEDORA_VERSION $BUILD_TAG"
        git push origin $BUILD_TAG
